CONSUL_HOST: 172.16.20.12
DOCKER_CLIENT_KEY: ./config/certs/client-key.pem
DOCKER_CLIENT_CERT: ./config/certs/client-cert.pem
DOCKER_SERVER_CERT: ./config/certs/ca.pem
#CONSUL_ACL_TOKEN: 6QTrYi2InPYJyfK7e50aCw==
CONSUL_ACL_TOKEN: FA4CD2F0-EF8A-4246-A602-D93A3E2E5EBE
CREATE_NETWORK_AUTOMATICALLY: false
DOCKER_NETWORK: net2
IPALLOC_RANGE: 10.0.10.0/25
GATEWAY_IP: 10.0.10.1
LISTEN_ADDR: 127.0.0.1
LISTEN_PORT: 5061

#HTTP_BASIC_USERNAME: admin
#HTTP_BASIC_PASSWORD: ilikerandompasswords
#BACKUP_DIR: /tmp/backups
#SSL_CERTFILE: cert.pem
#SSL_KEYFILE: key.pem
