---
driver:
  name: vagrant
  customize:
    memory: 2048

platforms:
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04
      image: ubuntu-16-04-x64

suites:
  - name: node1
    driver:
      vm_hostname: node1
    driver:
      network:
        - ["private_network", {ip: "172.16.20.12"}]

  - name: node2
    driver:
      vm_hostname: node2
    driver:
      network:
        - ["private_network", {ip: "172.16.20.13"}]

  - name: node3
    driver:
      vm_hostname: node3
    driver:
      network:
        - ["private_network", {ip: "172.16.20.14"}]

  - name: node4
    driver:
      vm_hostname: node4
    driver:
      network:
        - ["private_network", {ip: "172.16.20.15"}]
